# -*- coding: utf-8 -*-
"""starter_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-t5_Bu5sTfRbav4xJFtlHR8948N99e8
"""

```python
# Restaurant Review Sentiment Analysis

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


# TODO: Load the restaurant review dataset
df = pd.read_csv("../data/restaurant_reviews.csv")


# TODO: Explore the dataset
print(df.head())


# TODO: Identify the review text column and rating column


# TODO: Remove missing review text


# TODO: Create sentiment labels
# Example:
# 1–2 stars = negative
# 3 stars = neutral
# 4–5 stars = positive


# TODO: Examine class distribution


# TODO: Split the dataset into training and testing sets


# TODO: Vectorize the review text using TF-IDF


# Example Logistic Regression setup
model = LogisticRegression(max_iter=1000)


# TODO: Train the model


# TODO: Generate predictions


# TODO: Evaluate the model using:
# - Accuracy
# - Precision
# - Recall
# - F1-score


# TODO: Create a confusion matrix visualization

```